#
# docker-compose.yml — определяет сервисы для разработки и тестирования.
#

services:
  card-db:
    image: postgres:17
    container_name: card-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -h 127.0.0.1 -p 5432 -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: unless-stopped

  bank_rest:
    build: .
    container_name: bank-rest-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://card-db:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"

      JWT_SECRET: "${JWT_SECRET}"
      ENCRYPTOR_PASSWORD: "${ENCRYPTOR_PASSWORD}"
      ENCRYPTOR_SALT: "${ENCRYPTOR_SALT}"
      APP_HASHENCODER_PEPPER: "${APP_HASHENCODER_PEPPER}"

      # Hibernate не генерит схему (только проверка после Liquibase)
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"

      # Liquibase включен и changelog задан явно
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: "classpath:db/migration/db.changelog-master.yaml"

      # Успокаиваем логи (переопределяет application.yml при желании)
      LOGGING_LEVEL_ROOT: "INFO"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "INFO"
      LOGGING_LEVEL_LIQUIBASE: "INFO"
      LOGGING_LEVEL_COM_ZAXXER_HIKARI: "INFO"

      APP_ADMIN_EMAIL: "${APP_ADMIN_EMAIL}"
      APP_ADMIN_NAME: "${APP_ADMIN_NAME}"
      APP_ADMIN_PASSWORD: "${APP_ADMIN_PASSWORD}"


    depends_on:
      card-db:
        condition: service_healthy
    restart: unless-stopped