# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

services:
  card-db:
    image: postgres:17
    container_name: card-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  bank_rest:
    build: .
    container_name: bank-rest-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://card-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTOR_PASSWORD: ${ENCRYPTOR_PASSWORD}
      ENCRYPTOR_SALT: ${ENCRYPTOR_SALT}
    depends_on:
      card-db:
        condition: service_healthy
    restart: unless-stopped
